spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_mybatis
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  servlet:
    context-path: /demo
  port: 80
