spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 135246
    driver-class-name: com.mysql.jdbc.Driver

  datasource2:
    url: jdbc:presto://localhost:8080
    username: root
    password:
    driver-class-name: com.facebook.presto.jdbc.PrestoDriver
  redis:
    host: 127.0.0.1
    #cluster:
    #  nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
server:
  servlet:
    context-path: /demo
  port: 8000

mybatis:
  mapper-locations: classpath:/xml/*

rocketmq:
  name-server: 127.0.0.1:9876



